### ISSUE TITLE
Create a 4 motor drive train

### ISSUE THREAD

**Issue by cpostbitbuckets** [BitBucketsFRC4183/FRC2019_Destination_Deep_Space#1]
Create a subsystem interface and implementation for implementing drive related functions, including operational modes, test and diagnotic functions, and telemetry
- [x] Define a Drive Subsystem Class
- [x] Add Motor Controller Instances to Drive Subsystem Class
- [x] Define Minimum Access Functions for Drive Subsystem

**Comment by RocketRedNeck** [comment]
Handled by bring in last year's Drive Subsystem
